/**
 * NCGAS Base Stylesheet — exported as a JS string so the same CSS can be
 * (a) injected by the editor and (b) embedded verbatim by Compiler.gs into
 * every compiled app's Index.html. Class prefix: nc-
 */
(function (global) {
  'use strict';

  var BASE_CSS = [
    ':root{',
    '  --nc-bg:#0f1117;--nc-panel:#171a23;--nc-panel-2:#1e2230;--nc-border:#2a2f3f;',
    '  --nc-text:#e6e9f2;--nc-text-dim:#9aa3b8;--nc-accent:#4f7cff;--nc-accent-2:#7a5cff;',
    '  --nc-ok:#2fbf71;--nc-warn:#e8b33f;--nc-err:#e5534b;--nc-radius:10px;',
    '  --nc-font:system-ui,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;',
    '}',
    '.nc-theme-light{',
    '  --nc-bg:#f4f6fb;--nc-panel:#ffffff;--nc-panel-2:#eef1f8;--nc-border:#d8deea;',
    '  --nc-text:#1c2233;--nc-text-dim:#5d6780;',
    '}',
    '.nc-app{min-height:100vh;display:flex;flex-direction:column;background:var(--nc-bg);color:var(--nc-text);font-family:var(--nc-font);font-size:14px;}',
    '.nc-topbar{display:flex;align-items:center;gap:16px;padding:10px 20px;background:var(--nc-panel);border-bottom:1px solid var(--nc-border);flex:none;}',
    '.nc-topbar-title{font-weight:700;font-size:15px;flex:1;}',
    '.nc-topbar-user{color:var(--nc-text-dim);font-size:12px;}',
    // shell: slim top header + left sidebar menu + scrollable page content
    '.nc-shell{display:flex;flex:1;min-height:0;}',
    '.nc-sidebar{width:220px;flex:none;overflow-y:auto;background:var(--nc-panel);border-right:1px solid var(--nc-border);padding:14px 10px;display:flex;flex-direction:column;gap:2px;}',
    '.nc-shell-main{flex:1;min-width:0;display:flex;flex-direction:column;overflow-y:auto;}',
    '.nc-main{padding:24px;display:flex;justify-content:center;}',
    '.nc-menu-link{display:flex;align-items:center;gap:8px;background:none;border:none;color:var(--nc-text-dim);padding:9px 10px;border-radius:8px;cursor:pointer;font:inherit;font-size:13px;text-align:left;width:100%;}',
    '.nc-menu-link:hover{background:var(--nc-panel-2);color:var(--nc-text);}',
    '.nc-menu-active{background:var(--nc-panel-2);color:var(--nc-accent);font-weight:600;}',
    '.nc-menu-icon{flex:none;width:18px;text-align:center;}',
    '.nc-menu-label{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
    '.nc-menu-caret{flex:none;font-size:10px;color:var(--nc-text-dim);}',
    '.nc-menu-group-toggle{font-weight:600;}',
    '.nc-menu-children{display:flex;flex-direction:column;gap:2px;padding-left:14px;margin-top:2px;}',
    '.nc-menu-divider{border:none;border-top:1px solid var(--nc-border);margin:8px 4px;}',
    '.nc-page{width:100%;}',
    '.nc-row{width:100%;min-width:0;}',
    '.nc-cell{min-width:0;}',
    '.nc-heading{margin:0 0 4px;font-weight:700;}',
    '.nc-text{margin:0;color:var(--nc-text-dim);line-height:1.55;}',
    '.nc-divider{border:none;border-top:1px solid var(--nc-border);margin:8px 0;grid-column:1/-1;}',
    '.nc-field{display:flex;flex-direction:column;gap:6px;}',
    '.nc-field-inline{flex-direction:row;align-items:center;gap:8px;flex-wrap:wrap;}',
    '.nc-label{font-size:12px;font-weight:600;color:var(--nc-text-dim);letter-spacing:.02em;}',
    '.nc-label-inline{font-size:13px;}',
    '.nc-input{background:var(--nc-panel-2);border:1px solid var(--nc-border);color:var(--nc-text);border-radius:8px;padding:9px 12px;font:inherit;width:100%;box-sizing:border-box;outline:none;}',
    '.nc-input:focus{border-color:var(--nc-accent);}',
    '.nc-input:disabled{opacity:.65;}',
    '.nc-checkbox{width:16px;height:16px;accent-color:var(--nc-accent);}',
    // FORM_SELECT searchable combobox
    '.nc-combobox{position:relative;}',
    '.nc-combobox-box{position:relative;}',
    '.nc-combobox-box .nc-input{padding-right:28px;}',
    '.nc-combobox-clear{position:absolute;right:6px;top:50%;transform:translateY(-50%);width:20px;height:20px;border:none;background:none;color:var(--nc-text-dim);cursor:pointer;font-size:14px;line-height:1;}',
    '.nc-combobox-clear:hover{color:var(--nc-text);}',
    '.nc-combobox-list{position:absolute;top:calc(100% + 4px);left:0;right:0;z-index:20;background:var(--nc-panel);border:1px solid var(--nc-border);border-radius:8px;max-height:220px;overflow-y:auto;box-shadow:0 12px 30px rgba(0,0,0,.35);}',
    '.nc-combobox-option{padding:8px 12px;cursor:pointer;font-size:13px;}',
    '.nc-combobox-option:hover{background:var(--nc-panel-2);}',
    '.nc-combobox-option.is-selected{color:var(--nc-accent);font-weight:600;}',
    '.nc-combobox-empty{padding:8px 12px;color:var(--nc-text-dim);font-size:12px;}',
    '.nc-error{color:var(--nc-err);font-size:12px;}',
    '.nc-btn{background:linear-gradient(135deg,var(--nc-accent),var(--nc-accent-2));color:#fff;border:none;border-radius:8px;padding:10px 18px;font:inherit;font-weight:600;cursor:pointer;justify-self:start;}',
    '.nc-btn:hover{filter:brightness(1.1);}',
    '.nc-btn:disabled{opacity:.55;cursor:not-allowed;}',
    '.nc-btn-secondary{background:var(--nc-panel-2);color:var(--nc-text);border:1px solid var(--nc-border);}',
    '.nc-kpi{background:var(--nc-panel);border:1px solid var(--nc-border);border-radius:var(--nc-radius);padding:16px;}',
    '.nc-kpi-label{font-size:12px;color:var(--nc-text-dim);margin-bottom:6px;}',
    '.nc-kpi-value{font-size:24px;font-weight:700;}',
    '.nc-table-wrap{background:var(--nc-panel);border:1px solid var(--nc-border);border-radius:var(--nc-radius);overflow:auto;}',
    '.nc-table-title{padding:12px 14px;font-weight:600;border-bottom:1px solid var(--nc-border);}',
    '.nc-table{width:100%;border-collapse:collapse;font-size:13px;}',
    '.nc-table th{text-align:left;padding:10px 14px;color:var(--nc-text-dim);font-weight:600;border-bottom:1px solid var(--nc-border);white-space:nowrap;}',
    '.nc-table td{padding:10px 14px;border-bottom:1px solid var(--nc-border);}',
    '.nc-table tbody tr:last-child td{border-bottom:none;}',
    '.nc-table tbody tr:hover{background:var(--nc-panel-2);}',
    '.nc-table-empty{color:var(--nc-text-dim);text-align:center;}',
    '.nc-notice{padding:10px 20px;font-size:13px;cursor:pointer;display:flex;justify-content:space-between;gap:12px;}',
    '.nc-notice-error{background:rgba(229,83,75,.15);color:#ff8a84;border-bottom:1px solid rgba(229,83,75,.3);}',
    '.nc-notice-success{background:rgba(47,191,113,.12);color:#5fd99a;border-bottom:1px solid rgba(47,191,113,.3);}',
    '.nc-notice-info{background:rgba(79,124,255,.12);color:#8fb0ff;border-bottom:1px solid rgba(79,124,255,.3);}',
    '.nc-notice-x{opacity:.7;}',
    '.nc-unknown{background:rgba(229,83,75,.1);border:1px dashed var(--nc-err);color:var(--nc-err);padding:12px;border-radius:8px;font-size:12px;}',
    // small icon button — used by CRUD_TABLE row actions and modal close
    '.nc-celltool{width:24px;height:24px;font-size:11px;line-height:1;border-radius:6px;background:var(--nc-panel-2);border:1px solid var(--nc-border);color:var(--nc-text-dim);cursor:pointer;margin-left:4px;}',
    '.nc-celltool:hover{color:var(--nc-text);border-color:var(--nc-accent);}',
    '.nc-celltool.is-danger:hover{color:var(--nc-err);border-color:var(--nc-err);}',
    '.nc-celltool:disabled{opacity:.5;cursor:not-allowed;}',
    // CRUD_TABLE: toolbar (search + filters + add), row actions, master-detail selection
    '.nc-crud-wrap{position:relative;}',
    '.nc-crud-toolbar{display:flex;flex-wrap:wrap;gap:8px;padding:10px 14px;border-bottom:1px solid var(--nc-border);align-items:center;}',
    '.nc-crud-search,.nc-crud-filter{background:var(--nc-bg);border:1px solid var(--nc-border);color:var(--nc-text);border-radius:7px;padding:7px 10px;font:inherit;font-size:12px;min-width:120px;}',
    '.nc-crud-add{margin-left:auto;padding:7px 14px;font-size:12px;}',
    '.nc-crud-row{cursor:pointer;}',
    '.nc-crud-row-selected{background:rgba(79,124,255,.1);}',
    '.nc-crud-row-selected:hover{background:rgba(79,124,255,.14);}',
    '.nc-crud-actions-head{width:1%;white-space:nowrap;}',
    '.nc-crud-actions{white-space:nowrap;text-align:right;}',
    '.nc-crud-confirm-text{font-size:11px;color:var(--nc-warn);margin-right:4px;}',
    // rollup status badges (CRUD_TABLE)
    '.nc-badge{display:inline-block;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:600;letter-spacing:.02em;}',
    '.nc-badge-ok{background:rgba(47,191,113,.15);color:#5fd99a;}',
    '.nc-badge-warn{background:rgba(232,179,63,.15);color:#e8b33f;}',
    '.nc-badge-err{background:rgba(229,83,75,.15);color:#ff8a84;}',
    '.nc-badge-dim{background:var(--nc-panel-2);color:var(--nc-text-dim);}',
    // modal overlay for add/edit forms
    '.nc-modal-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.55);display:flex;align-items:center;justify-content:center;z-index:100;padding:20px;}',
    '.nc-modal-panel{background:var(--nc-panel);border:1px solid var(--nc-border);border-radius:12px;width:100%;max-width:480px;max-height:86vh;display:flex;flex-direction:column;box-shadow:0 20px 60px rgba(0,0,0,.5);}',
    '.nc-modal-head{display:flex;justify-content:space-between;align-items:center;padding:14px 18px;border-bottom:1px solid var(--nc-border);font-weight:700;}',
    '.nc-modal-body{padding:16px 18px;overflow-y:auto;display:flex;flex-direction:column;gap:14px;}',
    '.nc-modal-foot{display:flex;justify-content:flex-end;gap:8px;padding:14px 18px;border-top:1px solid var(--nc-border);}',
    '.nc-modal-error{margin:0 18px;padding:8px 10px;background:rgba(229,83,75,.12);border-radius:8px;}',
    // PRINT_BUTTON receipt view
    '.nc-print-panel{max-width:420px;}',
    '.nc-print-area{padding:16px 18px;font-family:ui-monospace,Consolas,monospace;font-size:12px;line-height:1.6;color:var(--nc-text);overflow-y:auto;}',
    '.nc-print-items{width:100%;border-collapse:collapse;margin:10px 0;font-size:11px;}',
    '.nc-print-items th,.nc-print-items td{padding:4px 6px;border-bottom:1px dashed var(--nc-border);text-align:left;}',
    '.nc-print-empty{color:var(--nc-text-dim);}',
    '@media print{body *{visibility:hidden;}.nc-print-area,.nc-print-area *{visibility:visible;}.nc-print-area{position:fixed;top:0;left:0;width:100%;padding:20px;color:#000;background:#fff;}}',
    // CHART
    '.nc-chart-wrap{background:var(--nc-panel);border:1px solid var(--nc-border);border-radius:var(--nc-radius);padding:14px;width:100%;box-sizing:border-box;}',
    '.nc-chart-canvas-wrap{position:relative;width:100%;height:260px;}',
    // FORM_IMAGE_UPLOAD + CRUD_TABLE image column/cell
    '.nc-image-upload{display:flex;gap:12px;align-items:flex-start;}',
    '.nc-image-preview{width:80px;height:80px;object-fit:cover;border-radius:8px;border:1px solid var(--nc-border);background:var(--nc-panel-2);}',
    '.nc-image-placeholder{width:80px;height:80px;display:flex;align-items:center;justify-content:center;text-align:center;font-size:10px;color:var(--nc-text-dim);background:var(--nc-panel-2);border:1px dashed var(--nc-border);border-radius:8px;padding:4px;box-sizing:border-box;}',
    '.nc-image-actions{display:flex;flex-direction:column;gap:6px;}',
    '.nc-image-pick{position:relative;display:inline-block;background:var(--nc-panel-2);color:var(--nc-text);border:1px solid var(--nc-border);border-radius:8px;padding:8px 14px;font:inherit;font-weight:600;cursor:pointer;text-align:center;}',
    '.nc-image-pick:hover{border-color:var(--nc-accent);}',
    '.nc-image-pick.is-disabled{opacity:.55;cursor:not-allowed;}',
    '.nc-image-file-input{position:absolute;width:1px;height:1px;opacity:0;overflow:hidden;}',
    '.nc-table-image{width:36px;height:36px;object-fit:cover;border-radius:6px;vertical-align:middle;}',
    '.nc-crud-field{display:flex;flex-direction:column;gap:6px;}',
    // design-mode affordances (editor canvas only)
    '.nc-cell-design{position:relative;border:1px dashed transparent;border-radius:8px;padding:22px 8px 8px;cursor:pointer;transition:border-color .12s;}',
    '.nc-cell-design:hover{border-color:var(--nc-border);}',
    '.nc-cell-selected{border-color:var(--nc-accent)!important;background:rgba(79,124,255,.06);}',
    '.nc-cell-ghost{opacity:.45;}',
    '.nc-cell-tag{position:absolute;top:3px;left:8px;font-size:10px;color:var(--nc-text-dim);letter-spacing:.03em;user-select:none;}',
    '.nc-cell-design .nc-btn,.nc-cell-design .nc-input,.nc-cell-design .nc-checkbox{pointer-events:none;}'
  ].join('\n');

  var api = { BASE_CSS: BASE_CSS };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  global.NCGASBaseCss = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
