/**
 * sync-gas — materializes the single-source shared/ core into the GAS builder
 * project. Run via `npm run sync:gas` (or `npm run build:gas`, which also
 * bundles the editor). Everything it writes is generated; never hand-edit.
 *
 *   shared/expression-engine.js -> gas/builder/ExpressionEngine.js  (builder server runtime)
 *                                -> gas/builder/Eng_Expression.html  (compiler payload for targets)
 *   shared/blueprint-utils.js   -> gas/builder/BlueprintUtils.js    (builder server runtime)
 *   shared/runtime-core.js      -> gas/builder/Eng_Runtime.html     (compiler payload)
 *   shared/base-css.js          -> gas/builder/BaseCss.js           (builder server runtime)
 *                                -> gas/builder/Eng_BaseCss.html     (compiler payload)
 *   dist-gas/index.html         -> gas/builder/Index_Builder.html   (the editor itself, if built)
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const gasDir = path.join(root, 'gas', 'builder');

const BANNER = '/* GENERATED by scripts/sync-gas.mjs from shared/ — DO NOT EDIT */\n';

function read(rel) {
  const p = path.join(root, rel);
  if (!fs.existsSync(p)) throw new Error(`[sync-gas] missing source file: ${rel}`);
  return fs.readFileSync(p, 'utf8');
}
function write(rel, content) {
  const p = path.join(gasDir, rel);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content);
  console.log(`  ✓ gas/builder/${rel} (${(content.length / 1024).toFixed(1)} KB)`);
}

console.log('[sync-gas] syncing shared core into gas/builder/');

const expression = read('shared/expression-engine.js');
const blueprint = read('shared/blueprint-utils.js');
const runtime = read('shared/runtime-core.js');
const baseCss = read('shared/base-css.js');

// builder server runtime copies (plain .js -> pushed as .gs by clasp)
write('ExpressionEngine.js', BANNER + expression);
write('BlueprintUtils.js', BANNER + blueprint);
write('BaseCss.js', BANNER + baseCss);

// compiler payloads (raw JS stored as .html so getRawContent() can read them)
write('Eng_Expression.html', BANNER + expression);
write('Eng_Runtime.html', BANNER + runtime);
write('Eng_BaseCss.html', BANNER + baseCss);

// the built editor SPA, when present
const editorBundle = path.join(root, 'dist-gas', 'index.html');
if (fs.existsSync(editorBundle)) {
  write('Index_Builder.html', fs.readFileSync(editorBundle, 'utf8'));
} else {
  console.log('  ! dist-gas/index.html not found — run `npm run build:gas` to bundle the editor for GAS hosting');
}

console.log('[sync-gas] done. Next: cd gas/builder && clasp push');
